### ISSUE TITLE
We need to remove the usage of InsecureSkipVerify: true

### ISSUE THREAD

**Issue by sharovik** [sharovik/devbot#103]
Basically, we can even remove this code at all
```
TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
```

https://github.com/sharovik/devbot/blob/1fa7925a6b308f252d324ceb70372f08683fc7b7/internal/container/container.go#L38-L38

**Comment by shoaibi** [comment]
I would suggest not to remove it but allow the users to pass it in, defaulting to false.

**Comment by sharovik** [comment]
Yeah, make sense!
