### ISSUE TITLE
Decrease to 0

### ISSUE THREAD

**Issue by sharovik** [sharovik/devbot#104]
https://github.com/sharovik/devbot/blob/1fa7925a6b308f252d324ceb70372f08683fc7b7/internal/service/slack/slack_message_service.go#L99

If we do change this from 1 to 0, this will give us the possibility to use the "single question" scenarios, which is pretty good!

**Comment by shoaibi** [comment]
![image](https://user-images.githubusercontent.com/809651/116891342-df508000-ac2e-11eb-941a-ca643341287d.png)
