### ISSUE TITLE
Change to Compile

### ISSUE THREAD

**Issue by sharovik** [sharovik/devbot#46]
https://github.com/sharovik/devbot/blob/cc05dc6a0d2a19eb3fcd75a614878a6c693873b1/internal/helper/helper.go#L141

We need to change MustCompile to Compile and throw an error if the regex did not compile. Otherwise, the panic will be triggered

**Comment by zachhweed** [comment]
I'm fine to take this. Just for clarification, we're looking for something like this right?
```go
re, err := regexp.Compile(regex)

if err != nil {
  log.Logger().AddError(err).Msg("Error during the find operation") 
}
```

**Comment by sharovik** [comment]
@zachhweed , yes )

**Comment by sharovik** [comment]
We have an error now
```internal/helper/helper.go:144:4: undefined: log```
Can you please put the `"github.com/sharovik/devbot/internal/log"` into import? This will fix that issue, thank you :)

**Comment by zachhweed** [comment]
Sure thing.

**Comment by sharovik** [comment]
Thank you!
